export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_RESTAURANT_DATA: 'SET_RESTAURANT_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_RESTAURANT_DATA: 'RESET_RESTAURANT_DATA',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	SET_USER_FAVORITES: 'SET_USER_FAVORITES',
};
