export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_USER_FAVORITES: 'SET_USER_FAVORITES',
	LOGOUT: 'LOGOUT',

	FETCH_RESTAURANTS_REQUEST: 'FETCH_RESTAURANTS_REQUEST',
	FETCH_RESTAURANTS_SUCCESS: 'FETCH_RESTAURANTS_SUCCESS',
	FETCH_RESTAURANTS_FAILURE: 'FETCH_RESTAURANTS_FAILURE',

	SET_RESTAURANT_REQUEST: 'SET_RESTAURANT_REQUEST',
	SET_RESTAURANT_SUCCESS: 'SET_RESTAURANT_SUCCESS',
	SET_RESTAURANT_FAILURE: 'SET_RESTAURANT_FAILURE',

	RESET_RESTAURANT_DATA: 'RESET_RESTAURANT_DATA',

	ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',

	REMOVE_COMMENT: 'REMOVE_COMMENT',
} as const;
